name: Lean CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mylean
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lean toolchain
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "mylean"
      - name: build
        run: lake build mynat binom modulo 